# Generated by Django 3.0 on 2021-01-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phonecode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=100, null=True)),
                ('addressline3', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.CountryList')),
            ],
        ),
        migrations.CreateModel(
            name='NewPatientAppointmentevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingPatientAppointmentevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(blank=True, editable=False, max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='CheckedinPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkedintime', models.DateTimeField(auto_now_add=True)),
                ('checkouttime', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
            ],
        ),
    ]
