# Generated by Django 3.0 on 2021-01-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionactivities', '0002_auto_20210105_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatientappointmentevents',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient'),
        ),
    ]
