# Generated by Django 3.0 on 2021-01-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receptionactivities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genericname', models.CharField(max_length=100)),
                ('medicine', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=4000, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('amount', models.FloatField()),
                ('taxpercentage', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatmentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('teeth', models.CharField(max_length=10)),
                ('fee', models.FloatField()),
                ('discount', models.FloatField()),
                ('payable', models.FloatField()),
                ('clinical_notes', models.CharField(max_length=4000)),
                ('status', models.CharField(max_length=10, null=True)),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctoractivities.Diagnosis')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctoractivities.Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Radilogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedfile', models.FileField(null=True, upload_to='')),
                ('documenttype', models.CharField(max_length=10, null=True)),
                ('toothno', models.IntegerField(null=True)),
                ('instructions', models.CharField(max_length=4000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('requesttype', models.CharField(max_length=10, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.IntegerField()),
                ('days', models.CharField(max_length=10)),
                ('instructions', models.CharField(max_length=4000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctoractivities.Medicine')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdate', models.DateField(auto_now_add=True)),
                ('mode', models.CharField(max_length=100)),
                ('transactionamount', models.FloatField()),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodpressure', models.BooleanField()),
                ('bloodpressuretext', models.CharField(max_length=1000, null=True)),
                ('heartalignment', models.BooleanField()),
                ('heartalignmenttext', models.CharField(max_length=1000, null=True)),
                ('heumaticfever', models.BooleanField()),
                ('heumaticfevertext', models.CharField(max_length=1000, null=True)),
                ('asthma', models.BooleanField()),
                ('asthmatext', models.CharField(max_length=1000, null=True)),
                ('tuberculosis', models.BooleanField()),
                ('tuberculosistext', models.CharField(max_length=1000, null=True)),
                ('heart', models.BooleanField()),
                ('hearttext', models.CharField(max_length=1000, null=True)),
                ('dentalissues', models.BooleanField()),
                ('dentalissuestext', models.CharField(max_length=1000, null=True)),
                ('previousillness', models.BooleanField()),
                ('previousillnesstext', models.CharField(max_length=1000, null=True)),
                ('presentmedicalcare', models.BooleanField()),
                ('presentmedicalcaretext', models.CharField(max_length=1000, null=True)),
                ('anydrugs', models.BooleanField()),
                ('anydrugstext', models.CharField(max_length=1000, null=True)),
                ('femalepatients', models.BooleanField()),
                ('femalepatientstext', models.CharField(max_length=1000, null=True)),
                ('alertallergies', models.BooleanField()),
                ('alertallergiestext', models.CharField(max_length=1000, null=True)),
                ('remarks', models.CharField(max_length=4000, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionactivities.Patient')),
            ],
        ),
    ]
