# Generated by Django 3.0 on 2021-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctoractivities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdetails',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
